const now = new Date();

export const events = [
    {
        id: "5uQgBLyANcgJm1GTviAB",
        name: "Chateau Margaux Balneário Camboriú",
        organizerId: "gwo0ujvzMqNgfq0Z5281b4jWKot1",
        dateStart: new Date(1748142000 * 1000),
        dateEnd: null,
        wines: {
            name: "Carbenet Sauvignon",
            harvest: "2020",
            country: "France",
            type: "Carbenet",
            description: "Descrição breve do vinho.",
            image: require("../assets/images/wine-6.jpg"),
        },
        participants: [
            {
                name: "João da Silva",
                id: "DZCPa2etXK1fydUzvcn",
                username: "@joaosilva",
                type: "organizer",
                email: "joao@ivino.com",
            },
        ],
        status: "INICIADO",
    },
    {
        id: "GsAEm74NHEzGLApOzMax",
        name: "Jantar Privado",
        organizerId: "gwo0ujvzMqNgfq0Z5281b4jWKot1",
        dateStart: new Date("2025-05-25"),
        dateEnd: new Date("2025-05-28"),
        wines: [
            {
                name: "Carbenet Sauvignon",
                harvest: "2020",
                country: "France",
                type: "Uva",
                description: "Descrição breve do vinho",
                image: require("../assets/images/wine-4.jpg"),
            },
        ],
        participants: [],
        status: "ENCERRADO",
    },
];

export const wines = [
    {
        id: "wine-1",
        name: "Cabernet Sauvignon Reserva",
        country: "Chile",
        ratings: {
            color: 4.5,
            aroma: 4.7,
            taste: 4.8,
        },
        average: 4.67,
        reviewsCount: 128,
        image: require("../assets/images/wine-1.jpg"),
    },
    {
        id: "wine-2",
        name: "Malbec Premium",
        country: "Argentina",
        ratings: {
            color: 4.2,
            aroma: 4.4,
            taste: 4.6,
        },
        average: 4.4,
        reviewsCount: 97,
        image: require("../assets/images/wine-2.jpg"),
    },
    {
        id: "wine-3",
        name: "Chardonnay Reserva",
        country: "Brasil",
        ratings: {
            color: 4.0,
            aroma: 4.3,
            taste: 4.1,
        },
        average: 4.13,
        reviewsCount: 56,
        image: require("../assets/images/wine-3.jpg"),
    },
    {
        id: "wine-4",
        name: "Syrah Grand Cuvée",
        country: "França",
        ratings: {
            color: 4.8,
            aroma: 4.9,
            taste: 5.0,
        },
        average: 4.9,
        reviewsCount: 243,
        image: require("../assets/images/wine-4.jpg"),
    },
    {
        id: "wine-5",
        name: "Merlot Delicado",
        country: "Portugal",
        ratings: {
            color: 4.1,
            aroma: 4.0,
            taste: 4.3,
        },
        average: 4.13,
        reviewsCount: 32,
        image: require("../assets/images/wine-5.jpg"),
    },
    {
        id: "wine-6",
        name: "Tempranillo Clássico",
        country: "Espanha",
        ratings: {
            color: 4.6,
            aroma: 4.4,
            taste: 4.5,
        },
        average: 4.5,
        reviewsCount: 88,
        image: require("../assets/images/wine-6.jpg"),
    },
    {
        id: "wine-7",
        name: "Pinot Noir Elegance",
        country: "França",
        ratings: {
            color: 4.3,
            aroma: 4.6,
            taste: 4.7,
        },
        average: 4.53,
        reviewsCount: 119,
        image: require("../assets/images/wine-7.jpg"),
    },
    {
        id: "wine-8",
        name: "Branco Suave",
        country: "Brasil",
        ratings: {
            color: 3.9,
            aroma: 4.1,
            taste: 4.0,
        },
        average: 4.0,
        reviewsCount: 45,
        image: require("../assets/images/wine-8.jpg"),
    },
    {
        id: "wine-9",
        name: "Zinfandel Rosé",
        country: "EUA",
        ratings: {
            color: 4.2,
            aroma: 4.0,
            taste: 4.3,
        },
        average: 4.17,
        reviewsCount: 67,
        image: require("../assets/images/wine-9.jpg"),
    },
    {
        id: "wine-10",
        name: "Espumante Brut Nature",
        country: "Itália",
        ratings: {
            color: 4.7,
            aroma: 4.6,
            taste: 4.8,
        },
        average: 4.7,
        reviewsCount: 101,
        image: require("../assets/images/wine-10.jpg"),
    },
];

export const winesUser = [
    {
        id: "1",
        name: "Vinho do Porto",
        vintage: "2006",
        country: "Portugal",
        grape: "Touriga Nacional",
        type: "Tinto",
        year: "2006",
        description: "Um clássico português com notas de ameixa e chocolate.",
        image: require("../assets/images/wine-1.jpg"),
        createdBy: "gwo0ujvzMqNgfq0Z5281b4jWKot1",
        createdAt: "2025-05-29",
        updatedAt: "2025-05-29",
    },
    {
        id: "2",
        name: "Château Margaux",
        vintage: "2015",
        country: "France",
        grape: "Cabernet Sauvignon",
        type: "Tinto",
        year: "2015",
        description: "Elegante e complexo, com taninos sedosos.",
        image: require("../assets/images/wine-5.jpg"),
        createdBy: "xYz123abc456def789ghi",
        createdAt: "2025-06-10",
        updatedAt: "2025-06-15",
    },
    {
        id: "3",
        name: "Cloudy Bay",
        vintage: "2021",
        country: "New Zealand",
        grape: "Sauvignon Blanc",
        type: "Branco",
        year: "2021",
        description: "Fresco e aromático, com notas de maracujá e capim-limão.",
        image: require("../assets/images/wine-3.jpg"),
        createdBy: "user789xyz123",
        createdAt: "2025-06-18",
        updatedAt: "2025-06-20",
    },
    {
        id: "4",
        name: "Amarone della Valpolicella",
        vintage: "2017",
        country: "Italy",
        grape: "Corvina Blend",
        type: "Tinto",
        year: "2017",
        description: "Corpo intenso com aromas de frutas secas e especiarias.",
        image: require("../assets/images/wine-4.jpg"),
        createdBy: "gwo0ujvzMqNgfq0Z5281b4jWKot1",
        createdAt: "2025-06-22",
        updatedAt: "2025-06-25",
    },
    {
        id: "5",
        name: "Concha y Toro Don Melchor",
        vintage: "2018",
        country: "Chile",
        grape: "Cabernet Sauvignon",
        type: "Tinto",
        year: "2018",
        description: "Potente e estruturado, com final longo e persistente.",
        image: require("../assets/images/wine-5.jpg"),
        createdBy: "chileWineLover22",
        createdAt: "2025-06-26",
        updatedAt: "2025-06-26",
    },
];
