-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiJdng4f+WGwzHLvE
kM9I0RKnQHwiDdfG7KPJtTiy58SgCgYIKoZIzj0DAQehRANCAAQO1Qnu3I+qsYsD
nqMQERZnc/IOfDHKMGvl2Vxt3ARCdvlxxPxqvmk8mhax2Egp1ujfc4vU1/PRnFFT
kkoA8Svr
-----END PRIVATE KEY-----